version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: EcommerceRedis_Prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network

  backend:
    image: ${DOCKER_USERNAME}/ecommerce-backend:latest
    container_name: EcommerceAPI_Prod
    ports:
      - "5092:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=EcommerceDB;User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379
      - JwtSettings__Secret=${JWT_SECRET}
      - MoMo__AccessKey=${MOMO_ACCESS_KEY}
      - MoMo__SecretKey=${MOMO_SECRET_KEY}
      - EmailSettings__Password=${EMAIL_PASSWORD}
    depends_on:
      - redis
    networks:
      - ecommerce-network

  frontend:
    image: ${DOCKER_USERNAME}/ecommerce-frontend:latest
    container_name: EcommerceWeb_Prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecommerce-network

volumes:
  redis_data:

networks:
  ecommerce-network:
    driver: bridge
