// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptops & Máy tính xách tay cao cấp",
                            IsDeleted = false,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gaming Gear & Phụ kiện Gaming",
                            IsDeleted = false,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thiết bị Âm thanh Cao cấp",
                            IsDeleted = false,
                            Name = "Audio"
                        },
                        new
                        {
                            Id = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smartphone & Thiết bị Di động",
                            IsDeleted = false,
                            Name = "Smartphones"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            ReservedQuantity = 0,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000005"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000006"),
                            ReservedQuantity = 0,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000007"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000008"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000009"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000010"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000011"),
                            ReservedQuantity = 0,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000012"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000013"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000014"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000015"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000016"),
                            ReservedQuantity = 0,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000017"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000018"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000019"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000020"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000021"),
                            ReservedQuantity = 0,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000022"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000023"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000023"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000024"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000024"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000025"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000025"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000026"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000026"),
                            ReservedQuantity = 0,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000027"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000027"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000028"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000028"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000029"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000029"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000030"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000031"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000031"),
                            ReservedQuantity = 0,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000032"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000032"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000033"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000033"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000034"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000034"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000035"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000035"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000036"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000036"),
                            ReservedQuantity = 0,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000037"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000037"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000038"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000038"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000039"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000039"),
                            ReservedQuantity = 0,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000040"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000040"),
                            ReservedQuantity = 0,
                            StockQuantity = 15
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PaymentMethod = "COD",
                            RecipientName = "Trần Thị Bình",
                            RecipientPhone = "0900000001",
                            ShippingAddress = "Số 10 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Pending",
                            TotalAmount = 52490000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PaymentMethod = "VietQR",
                            RecipientName = "Nguyễn Văn An",
                            RecipientPhone = "0900000002",
                            ShippingAddress = "Số 20 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Pending",
                            TotalAmount = 52490000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 17, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PaymentMethod = "MoMo",
                            RecipientName = "Trần Thị Bình",
                            RecipientPhone = "0900000003",
                            ShippingAddress = "Số 30 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Pending",
                            TotalAmount = 9450000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 18, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PaymentMethod = "COD",
                            RecipientName = "Nguyễn Văn An",
                            RecipientPhone = "0900000004",
                            ShippingAddress = "Số 40 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Confirmed",
                            TotalAmount = 4725000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 19, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PaymentMethod = "VietQR",
                            RecipientName = "Trần Thị Bình",
                            RecipientPhone = "0900000005",
                            ShippingAddress = "Số 50 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Confirmed",
                            TotalAmount = 6225000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PaymentMethod = "MoMo",
                            RecipientName = "Nguyễn Văn An",
                            RecipientPhone = "0900000006",
                            ShippingAddress = "Số 60 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Shipping",
                            TotalAmount = 12450000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PaymentMethod = "COD",
                            RecipientName = "Trần Thị Bình",
                            RecipientPhone = "0900000007",
                            ShippingAddress = "Số 70 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Shipping",
                            TotalAmount = 28990000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 6, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PaymentMethod = "VietQR",
                            RecipientName = "Nguyễn Văn An",
                            RecipientPhone = "0900000008",
                            ShippingAddress = "Số 80 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Delivered",
                            TotalAmount = 28990000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 6, 23, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PaymentMethod = "MoMo",
                            RecipientName = "Trần Thị Bình",
                            RecipientPhone = "0900000009",
                            ShippingAddress = "Số 90 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Delivered",
                            TotalAmount = 18980000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 6, 24, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Note = "Hủy do thay đổi kế hoạch",
                            PaymentMethod = "COD",
                            RecipientName = "Nguyễn Văn An",
                            RecipientPhone = "0900000010",
                            ShippingAddress = "Số 100 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Cancelled",
                            TotalAmount = 9490000m,
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d")
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            Quantity = 1,
                            UnitPrice = 52490000m
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            Quantity = 1,
                            UnitPrice = 52490000m
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 17, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000011"),
                            Quantity = 2,
                            UnitPrice = 4725000m
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 18, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000004"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000011"),
                            Quantity = 1,
                            UnitPrice = 4725000m
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 19, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000005"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000021"),
                            Quantity = 1,
                            UnitPrice = 6225000m
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000006"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000021"),
                            Quantity = 2,
                            UnitPrice = 6225000m
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000032"),
                            Quantity = 1,
                            UnitPrice = 28990000m
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 6, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000008"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000032"),
                            Quantity = 1,
                            UnitPrice = 28990000m
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 6, 23, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000009"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000035"),
                            Quantity = 2,
                            UnitPrice = 9490000m
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 6, 24, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("f0000000-0000-0000-0000-000000000010"),
                            ProductId = new Guid("d0000000-0000-0000-0000-000000000035"),
                            Quantity = 1,
                            UnitPrice = 9490000m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flagship laptop với Intel Core Ultra 9, RAM 32GB, màn OLED 4K, siêu mỏng 14mm.",
                            IsDeleted = false,
                            Name = "iLuminaty Pro X1",
                            Price = 52490000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop văn phòng 15 inch nhẹ 1.2kg, pin 20 giờ, AMD Ryzen 7 8845HS.",
                            IsDeleted = false,
                            Name = "iLuminaty Air 15",
                            Price = 28990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Workstation sáng tạo với RTX 4090, RAM 64GB ECC, thiết kế CNC aluminium.",
                            IsDeleted = false,
                            Name = "Phantom Studio Pro",
                            Price = 89900000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultrabook 13 inch gọn nhẹ, màn hình 2.8K AMOLED 120Hz, Intel Arc GPU.",
                            IsDeleted = false,
                            Name = "Nexus Book S13",
                            Price = 22590000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Business laptop bảo mật cấp cao, TPM 2.0, khuôn mặt IR, RAM 16GB LPDDR5X.",
                            IsDeleted = false,
                            Name = "Lumina Elite X Pro",
                            Price = 35990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop đồ họa chuyên dụng 16 inch, RTX 4070, bàn phím cơ Cherry MX.",
                            IsDeleted = false,
                            Name = "ProVision 16 Max",
                            Price = 45990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creator laptop màn 4K OLED touch, Ryzen 9 8945HX, card đồ họa Radeon 890M.",
                            IsDeleted = false,
                            Name = "Swift Creator X",
                            Price = 38500000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mỏng nhẹ nhất phân khúc, chỉ 0.9kg, màn 14 inch QHD+, pin 18 giờ.",
                            IsDeleted = false,
                            Name = "Nova Slim 14",
                            Price = 19990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gaming laptop 17 inch, RTX 4080 12GB, màn 240Hz QHD, tản nhiệt vapor chamber.",
                            IsDeleted = false,
                            Name = "Titan Gamer Pro",
                            Price = 58990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c61"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop cho lập trình viên, Linux ready, 32GB RAM, SSD 2TB NVMe PCIe 5.0.",
                            IsDeleted = false,
                            Name = "CodeBook Developer Ed.",
                            Price = 31990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000011"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bàn phím cơ không dây đỉnh cao, switch êm ái, đèn nền RGB per-key.",
                            IsDeleted = false,
                            Name = "Ghost Mechanical Keyboard",
                            Price = 4725000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000012"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chuột gaming 26000 DPI, sensor quang học, trọng lượng 58g siêu nhẹ.",
                            IsDeleted = false,
                            Name = "Phantom Mouse Pro X",
                            Price = 2990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000013"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mousepad gaming khổng lồ 900×400mm, bề mặt tốc độ cao, viền LED RGB.",
                            IsDeleted = false,
                            Name = "HyperPad XL RGB",
                            Price = 890000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000014"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ghế gaming ergonomic, đệm memory foam, tựa đầu 4D, chịu tải 150kg.",
                            IsDeleted = false,
                            Name = "Storm Gaming Chair",
                            Price = 8990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000015"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình gaming 27 inch QHD 165Hz, 1ms GTG, FreeSync Premium, HDR400.",
                            IsDeleted = false,
                            Name = "NitroView 27\" 165Hz",
                            Price = 9990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000016"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bảng điều khiển stream 32 phím LCD, tích hợp OBS, Twitch, Discord.",
                            IsDeleted = false,
                            Name = "StreamDeck Pro",
                            Price = 3490000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000017"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bàn phím compact 60%, hot-swap socket, keycap PBT double-shot.",
                            IsDeleted = false,
                            Name = "VortexKeys 60%",
                            Price = 2190000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000018"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tay cầm chơi game PC/Mobile, kết nối USB-C + Bluetooth, trigger haptic.",
                            IsDeleted = false,
                            Name = "CoreController Pro",
                            Price = 1990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000019"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Webcam gaming 4K 30fps, AI background removal, ring light LED tích hợp.",
                            IsDeleted = false,
                            Name = "UltraCapture 4K Cam",
                            Price = 3290000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000020"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c62"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Headset gaming 7.1 surround, mic khử ồn AI, đệm tai foam ngủ ngon.",
                            IsDeleted = false,
                            Name = "Aurora Gaming Headset",
                            Price = 2490000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000021"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tai nghe chống ồn ANC thế hệ 3, driver 11mm, pin 36 giờ kèm case.",
                            IsDeleted = false,
                            Name = "Sonic Buds Pro",
                            Price = 6225000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000022"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Micro condenser USB-C cho studio, cardioid/omnidirectional, 192kHz.",
                            IsDeleted = false,
                            Name = "CrystalAir Studio Mic",
                            Price = 4590000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000023"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loa Bluetooth 360 độ IPX7, bass mạnh, pin 24 giờ, kết nối đa điểm.",
                            IsDeleted = false,
                            Name = "BassBoom Speaker 360",
                            Price = 3190000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000024"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tai nghe over-ear cao cấp, driver planar 50mm, DAC tích hợp 32-bit.",
                            IsDeleted = false,
                            Name = "Lumina Over-Ear H1",
                            Price = 12990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000025"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thanh loa soundbar 2.1 kèm subwoofer, Dolby Atmos, HDMI ARC.",
                            IsDeleted = false,
                            Name = "AudioBar Pro 2.1",
                            Price = 8490000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000026"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TWS earbuds cho công việc, mic MEMS 4 array, ENC khử ồn, pin 28 giờ.",
                            IsDeleted = false,
                            Name = "VoiceLink Pro Earbuds",
                            Price = 3990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000027"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DAC/Amp di động, ES9038Q2M chip, power 300mW vào 32Ω, USB-C.",
                            IsDeleted = false,
                            Name = "PocketDAC Ultra",
                            Price = 5290000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000028"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "In-ear monitor 5 driver hybrid, cáp bạc 8 lõi, dải tần 8Hz-45kHz.",
                            IsDeleted = false,
                            Name = "SonicWave IEM S5",
                            Price = 9990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000029"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bộ podcast: mic arm + mic + pop filter + audio interface USB.",
                            IsDeleted = false,
                            Name = "ClearCast Podcast Kit",
                            Price = 4290000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000030"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c63"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Amplifier hi-fi cho loa passive, 2×100W class AB, Bluetooth 5.3.",
                            IsDeleted = false,
                            Name = "HomeAudio Amp X3",
                            Price = 6990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000031"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đồng hồ thông minh AMOLED 1.8\", đo SpO2/ECG/BP, GPS độc lập.",
                            IsDeleted = false,
                            Name = "Nexus Watch S",
                            Price = 9975000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000032"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flagship phone Snapdragon 8 Elite, camera 200MP, sạc 100W, IP68.",
                            IsDeleted = false,
                            Name = "iLuminaty Phone Pro",
                            Price = 28990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000033"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tablet 12 inch 2.8K 144Hz, M2 chip, 5G, bút stylus thế hệ 2.",
                            IsDeleted = false,
                            Name = "NovaPad Ultra 12",
                            Price = 22490000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000034"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smartphone màn hình gập 7.6 inch, chống nước IPX8, khung titan.",
                            IsDeleted = false,
                            Name = "FoldX Premium",
                            Price = 45990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000035"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smartphone tầm trung tốt nhất, Dimensity 7300, camera 108MP, pin 6000mAh.",
                            IsDeleted = false,
                            Name = "MidRange Hero A55",
                            Price = 9490000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000036"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vòng tay thể thao đo 24 chỉ số sức khỏe, pin 21 ngày, chống nước 5ATM.",
                            IsDeleted = false,
                            Name = "WristBand Fit Pro",
                            Price = 2490000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000037"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tablet trẻ em 8 inch, bảo vệ mắt EyeShield+, khóa ứng dụng theo độ tuổi.",
                            IsDeleted = false,
                            Name = "AirTab Kids 8",
                            Price = 4990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000038"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pin dự phòng 25000mAh, sạc 140W, 3 cổng ra, hiển thị số dung lượng.",
                            IsDeleted = false,
                            Name = "PowerBank Turbo 25K",
                            Price = 1990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000039"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kính AR thế hệ đầu, hiển thị thông tin ngay trên kính, kết nối BT 5.3.",
                            IsDeleted = false,
                            Name = "SmartGlasses AR-1",
                            Price = 15990000m
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000040"),
                            CategoryId = new Guid("c1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c64"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trạm sạc không dây 8 thiết bị cùng lúc, 100W tổng, chân đế sang trọng.",
                            IsDeleted = false,
                            Name = "ChargeStation 8-in-1",
                            Price = 3490000m
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SavedAddresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Address = "123 iLuminaty HQ, TP.HCM",
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@iluminaty.com",
                            FullName = "System Administrator",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$Le3WZPxhWsgyNrsgQ5oEEOQ6uCYXNMpEWZ14rRqQAkZejS75R/zJK",
                            PhoneNumber = "0901234567",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("f6e5d4c3-b2a1-0f9e-8d7c-6b5a4f3e2d1c"),
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@iluminaty.com",
                            FullName = "Store Operator",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$9Nm0pHWKVQg31ja3mv6en.MwVYy2fEp11Tn0kqATnBJIehM2iL/Ky",
                            PhoneNumber = "0907654321",
                            Role = "Staff"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("Domain.Entities.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
