name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB 1: Build & Kiểm tra Backend ---
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore src/WebAPI/WebAPI.csproj

      - name: Build Backend
        run: dotnet build src/WebAPI/WebAPI.csproj --configuration Release --no-restore

  # --- JOB 2: Build & Kiểm tra Frontend ---
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './ecommerce-web/package-lock.json'

      - name: Install Dependencies
        working-directory: ./ecommerce-web
        run: npm ci

      - name: Build React App
        working-directory: ./ecommerce-web
        run: npm run build

  # --- JOB 3: CD - Đóng gói Docker & Đẩy lên Docker Hub ---
  # Chỉ chạy Job này nếu đẩy code lên nhánh main VÀ 2 job Build ở trên thành công
  push-docker-image:
    needs: [build-backend, build-frontend]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug lỗi cấu hình Secrets
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Độ dài Username của bạn là: ${#DOCKER_USER} ký tự."
          echo "Độ dài Mật khẩu của bạn là: ${#DOCKER_PASS} ký tự."
          
          if [ "${#DOCKER_USER}" -eq 0 ]; then
            echo "LỖI: Username bị rỗng! GitHub không đọc được biến DOCKER_USERNAME."
            exit 1
          fi
          
          if [ "${#DOCKER_PASS}" -eq 0 ]; then
            echo "LỖI: Mật khẩu bị rỗng! GitHub không đọc được biến DOCKER_PASSWORD."
            exit 1
          fi

      - name: Đăng nhập vào Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./ecommerce-web
          file: ./ecommerce-web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest
